[1]
input = """
2
AAA
AAA
"""

output = """
1998
"""

[2]
input = """
2
GCF
ACDEB
"""

output = """
99437
"""

[3]
input = """
10
A
B
C
D
E
F
G
H
I
J
"""

output = """
45
"""

[4]
input = """
2
AB
BA
"""

output = """
187
"""

