[1]
input = """
2 3 1
"""

output = """
11
"""

[2]
input = """
3 7 7
"""

output = """
63
"""

[3]
input = """
1 0 0
"""

output = """
0
"""

[4]
input = """
4 7 7
"""

output = """
63
"""

[5]
input = """
10 511 511
"""

output = """
262143
"""

[6]
input = """
10 512 512
"""

output = """
786432
"""

