[1]
input = """
1
"""

output = """
*
"""

[2]
input = """
2
"""

output = """
*****
*   *
* * *
*   *
*****
"""

[3]
input = """
3
"""

output = """
*********
*       *
* ***** *
* *   * *
* * * * *
* *   * *
* ***** *
*       *
*********
"""

[4]
input = """
4
"""

output = """
*************
*           *
* ********* *
* *       * *
* * ***** * *
* * *   * * *
* * * * * * *
* * *   * * *
* * ***** * *
* *       * *
* ********* *
*           *
*************
"""

